version: '3.8'

services:
  web:
    build: .
    container_name: lmerapp-web
    environment:
      DB_DATABASE: "myapp"
      DB_USERNAME: "mysql"
      DB_PASSWORD: "res1216<3"
      DB_HOST: "db"
      DB_PORT: 3306
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lmerapp-db
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "myapp"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "res1216<3"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
